---
driver:
  name: vagrant

platforms:
  - name: centos-7.3
  - name: realreadme/amazon2016.09

provisioner:
  name: salt_solo
  formula: pygit2

suites:
  - name: server
    provisioner:
      state_top:
        base:
          '*':
            - pygit2

