---
driver:
  name: vagrant

platforms:
  - name: centos-7.3

provisioner:
  name: salt_solo
  formula: pygit2

suites:
  - name: server
    provisioner:
      state_top:
        base:
          '*':
            - libgit2
            - pygit2

